version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"

  print_environment_variable:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $NAME

  save_hello_world_output:
    docker:
      - image: alpine:latest
    steps:
      - run:
          command: |
            mkdir -p /tmp/workdir
            cd /tmp/workdir
            echo "Hello World" > output.txt
      - persist_to_workspace:
          root: /tmp/workdir
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: /tmp/workdir
      - run:
          command: |
            cd /tmp/workdir
            cat output.txt

  print_pipeline_id:
    docker:
      - image: alpine:latest
    steps:
      - print_pipeline_id

workflows:
  welcome:
    jobs:
      - print_pipeline_id