version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"

  print_environment_variable:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $NAME

  save_hello_world_output:
    docker:
      - image: alpine:latest
    steps:
      - run:
          command: |
            mkdir -p /tmp/workdir && cd $_
            pwd && echo "Hello World" > output.txt
            pwd && ls
      - persist_to_workspace:
          root: /tmp/workdir
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: /tmp/workdir
      - run: pwd && cat output.txt

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
